version: '3'

services:
    php-cli:
        build:
            context: etc/devel/docker
        image: php/php-cli
        container_name: miquel.php-console
        volumes:
            - ".:/app"
        extra_hosts:
            - "docker.host:${DOCKER_HOST_IP}"
        tty: true